apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ambient-code--team-tracker

resources:
- ../ai-eng

configMapGenerator:
- behavior: merge
  literals:
  - API_PUBLIC_URL=https://api-team-tracker.apps.int.spoke.prod.us-west-2.aws.paas.redhat.com
  - AUTH_EMAIL_DOMAIN=cluster.local
  name: team-tracker-config

patches:
- path: route-patch.yaml
- path: api-route-patch.yaml

images:
- name: quay.io/org-pulse/team-tracker-backend
  newTag: 4e0c3e6a0f32b574742f7e650a1cde1072ed1902
- name: quay.io/org-pulse/team-tracker-frontend
  newTag: c356383f73304c86f152c4cf72f101af2753bb21
