apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-pvc.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-route.yaml
  - api-route.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: team-tracker-config
    literals:
      - NODE_ENV=production
      - API_PORT=3001
      - JIRA_HOST=https://redhat.atlassian.net
      - ADMIN_EMAILS=acorvin@redhat.com,acorvin@cluster.local,jalberts@redhat.com
  - name: nginx-config-template
    files:
      - app.conf.template=nginx-app.conf.template
